### PR TITLE
Unity Package Manager fix

### LINKED ISSUE #24: upm support
Can we convert this into a UPM package to be used with https://github.com/mob-sakai/UpmGitExtension? I can do it for you if you don't have time.

### PR DESCRIPTION
**Pull request by Bullrich**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] No compiler errors or warnings

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Issue Number

Closes #24 

## What is the current behavior?

The project can not be used as a UPM project.

## What is the new behavior?

Fixed `package.json` and added an autotagging implementation to prepare the project to be uploaded at [OpenUPM](https://openupm.com/).

The auto tag implementation will tag releases when `package.json` version is upgraded. If this is not required, I can remove it from the PR.

Downgraded Unity version to 2018 LTS. You should use the lowest possible version of Unity when developing a plugin to ensure that you don't have a problem. Unity is not very friendly with plugin downgrading. I updated the `package.json` version to use this Unity version.

Once this change is merged, I'll update the [current package in OpenUPM](https://openupm.com/packages/com.svermeulen.extenject/) to point to this repository and make a new PR with the instructions of how to add this package using UPM.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I updated the gitignore because not every package was being ignored. 

On which Unity version has this been tested?
--------------------------------------------
- [ ] 2020.4 LTS
- [ ] 2020.3
- [ ] 2020.2
- [ ] 2020.1
- [ ] 2019.4 LTS
- [ ] 2019.3
- [ ] 2019.2
- [ ] 2019.1
- [x] 2018.4 LTS

**Scripting backend:**
- [ ] Mono
- [x] IL2CPP

### CODE REVIEW

**Comment by Bullrich** [comment]
There seem to be a problem with the Unity License in the CI process

**Comment by Bullrich** [comment]
@svermeulen could you look at this PR and the problem with the licensing?

**Comment by starikcetin** [comment]
Hey, can you give me a mention here when we merge this? We can then re-target the OpenUPM package to use this main repo instead of my fork. @Bullrich

**Comment by Bullrich** [comment]
> Hey, can you give me a mention here when we merge this? We can then re-target the OpenUPM package to use this main repo instead of my fork. @Bullrich

I've been trying to get @svermeulen attention but he replied on Glitter that he is busy lately. I don't know what we can do meanwhile. I can also open a PR pointing to your repo as a temporal solution

**Comment by starikcetin** [comment]
> > Hey, can you give me a mention here when we merge this? We can then re-target the OpenUPM package to use this main repo instead of my fork. @Bullrich
> 
> I've been trying to get @svermeulen attention but he replied on Glitter that he is busy lately. I don't know what we can do meanwhile.

I'll try to help you out when I get the chance. With the new subdirectory support in UPM, it shouldn't be very hard to get this PR rolling.

> I can also open a PR pointing to your repo as a temporal solution

I don't understand what you mean by this. Can you elaborate?

**Pull request closed without merging**
